
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.8.9-hotspot/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Program Files/HP/OMEN-Broadcast/Common/"
      - "C:/msys64/mingw64/bin/"
      - "C:/MinGW/bin/"
      - "C:/Program Files/dotnet/"
      - "C:/Users/Vatsal/Documents/fileMaker/"
      - "C:/Program Files/nodejs/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Program Files/Go/bin/"
      - "C:/sqlite/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Program Files/PostgreSQL/17/bin/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Program Files (x86)/Lua/5.1/"
      - "C:/Program Files (x86)/Lua/5.1/clibs/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Users/Vatsal/AppData/Local/Programs/Python/Python313/Scripts/"
      - "C:/Users/Vatsal/AppData/Local/Programs/Python/Python313/"
      - "C:/Users/Vatsal/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/Vatsal/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/Vatsal/AppData/Local/Microsoft/WinGet/Links/"
      - "C:/Users/Vatsal/Desktop/scrcpy-win64-v3.2/scrcpy-win64-v3.2/scrcpy.exe/"
      - "C:/Users/Vatsal/Desktop/scrcpy-win64-v3.2/scrcpy-win64-v3.2/adb.exe/"
      - "C:/Users/Vatsal/AppData/Roaming/npm/"
      - "C:/Users/Vatsal/go/bin/"
      - "C:/Users/Vatsal/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.8.9-hotspot/bin/mingw32-make.exe.com"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.8.9-hotspot/bin/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/mingw32-make.exe"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Program Files/HP/OMEN-Broadcast/Common/mingw32-make.exe.com"
      - "C:/Program Files/HP/OMEN-Broadcast/Common/mingw32-make.exe"
      - "C:/msys64/mingw64/bin/mingw32-make.exe.com"
      - "C:/msys64/mingw64/bin/mingw32-make.exe"
      - "C:/MinGW/bin/mingw32-make.exe.com"
      - "C:/MinGW/bin/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Users/Vatsal/Documents/fileMaker/mingw32-make.exe.com"
      - "C:/Users/Vatsal/Documents/fileMaker/mingw32-make.exe"
      - "C:/Program Files/nodejs/mingw32-make.exe.com"
      - "C:/Program Files/nodejs/mingw32-make.exe"
      - "C:/ProgramData/chocolatey/bin/mingw32-make.exe.com"
      - "C:/ProgramData/chocolatey/bin/mingw32-make.exe"
      - "C:/Program Files/Go/bin/mingw32-make.exe.com"
      - "C:/Program Files/Go/bin/mingw32-make.exe"
      - "C:/sqlite/mingw32-make.exe.com"
      - "C:/sqlite/mingw32-make.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe"
      - "C:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "C:/Program Files/Git/cmd/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/Program Files/PostgreSQL/17/bin/mingw32-make.exe.com"
      - "C:/Program Files/PostgreSQL/17/bin/mingw32-make.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/mingw32-make.exe.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/mingw32-make.exe"
      - "C:/Program Files (x86)/Lua/5.1/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Lua/5.1/mingw32-make.exe"
      - "C:/Program Files (x86)/Lua/5.1/clibs/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Lua/5.1/clibs/mingw32-make.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe.com"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe"
      - "C:/Users/Vatsal/AppData/Local/Programs/Python/Python313/Scripts/mingw32-make.exe.com"
      - "C:/Users/Vatsal/AppData/Local/Programs/Python/Python313/Scripts/mingw32-make.exe"
      - "C:/Users/Vatsal/AppData/Local/Programs/Python/Python313/mingw32-make.exe.com"
      - "C:/Users/Vatsal/AppData/Local/Programs/Python/Python313/mingw32-make.exe"
      - "C:/Users/Vatsal/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/Vatsal/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/Vatsal/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Users/Vatsal/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/Vatsal/AppData/Local/Microsoft/WinGet/Links/mingw32-make.exe.com"
      - "C:/Users/Vatsal/AppData/Local/Microsoft/WinGet/Links/mingw32-make.exe"
      - "C:/Users/Vatsal/Desktop/scrcpy-win64-v3.2/scrcpy-win64-v3.2/scrcpy.exe/mingw32-make.exe.com"
      - "C:/Users/Vatsal/Desktop/scrcpy-win64-v3.2/scrcpy-win64-v3.2/scrcpy.exe/mingw32-make.exe"
      - "C:/Users/Vatsal/Desktop/scrcpy-win64-v3.2/scrcpy-win64-v3.2/adb.exe/mingw32-make.exe.com"
      - "C:/Users/Vatsal/Desktop/scrcpy-win64-v3.2/scrcpy-win64-v3.2/adb.exe/mingw32-make.exe"
      - "C:/Users/Vatsal/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/Vatsal/AppData/Roaming/npm/mingw32-make.exe"
      - "C:/Users/Vatsal/go/bin/mingw32-make.exe.com"
      - "C:/Users/Vatsal/go/bin/mingw32-make.exe"
      - "C:/Users/Vatsal/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/mingw32-make.exe.com"
      - "C:/Users/Vatsal/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.8.9-hotspot\\bin"
        - "C:\\windows\\system32"
        - "C:\\windows"
        - "C:\\windows\\System32\\Wbem"
        - "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\windows\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Program Files\\HP\\OMEN-Broadcast\\Common"
        - "C:\\msys64\\mingw64\\bin"
        - "C:\\MinGW\\bin"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Users\\Vatsal\\Documents\\fileMaker\\"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Program Files\\Go\\bin"
        - "C:\\sqlite"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\PostgreSQL\\17\\bin\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\Lua\\5.1"
        - "C:\\Program Files (x86)\\Lua\\5.1\\clibs"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Users\\Vatsal\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\"
        - "C:\\Users\\Vatsal\\AppData\\Local\\Programs\\Python\\Python313\\"
        - "C:\\Users\\Vatsal\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Vatsal\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\Vatsal\\AppData\\Local\\Microsoft\\WinGet\\Links"
        - "C:\\Users\\Vatsal\\Desktop\\scrcpy-win64-v3.2\\scrcpy-win64-v3.2\\scrcpy.exe"
        - "C:\\Users\\Vatsal\\Desktop\\scrcpy-win64-v3.2\\scrcpy-win64-v3.2\\adb.exe"
        - "C:\\Users\\Vatsal\\AppData\\Roaming\\npm"
        - "C:\\Users\\Vatsal\\go\\bin"
        - "C:\\Users\\Vatsal\\AppData\\Local\\Google\\Cloud SDK\\google-cloud-sdk\\bin"
...
